version : '3.9'

services :
  # Python Application
  application :
    build : Python
    ports :
      - "8080:8080"
    depends_on :
      - tensor
    networks :
      - app-network
  # TensorFlow Model
  # Prometheus
  prometheus : 
    image : prom/prometheus:v3.1.0
    ports : 
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - app-network
  # Grafana

networks :
  app-network :
    driver : bridge